# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fone', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=255)),
            ],
        ),
    ]
